name: Ejecutar SQL desde carpeta db

on: [push]

jobs:
  run-sql:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repo
        uses: actions/checkout@v3

      - name: Instalar cliente PostgreSQL
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Ejecutar todos los scripts SQL en carpeta db
        env:
          PGPASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          echo "Ejecutando todos los archivos SQL en ./db..."

          find ./db -type f -name "*.sql" | sort | while read -r file; do
            echo "Ejecutando: $file"
            psql \
              -h ${{ secrets.DB_HOST }} \
              -U ${{ secrets.DB_USER }} \
              -d ${{ secrets.DB_NAME }} \
              -p ${{ secrets.DB_PORT }} \
              -f "$file"
          done
